name: donwloadArtifacts

on:
  workflow_dispatch: #テスト用手動実行イベント

jobs:
  build:
    runs-on: macos-latest
    environment: test
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat math-homework.txt`

          echo $value