name: Swift

on:
  pull_request:
    branches: [ main ]
    types: #pull requestがマージ時にのみ動かしたい
      - closed
  workflow_dispatch: #テスト用手動実行イベント

jobs:
  build:
    runs-on: macos-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - name: Cache SwiftPM
      uses: actions/cache@v2
      
      with: 
        path: |
          ./blackJack/.SPM
        key: ${{ hashFiles('**/Package.resolved') }}
    - name: test git branchName
      run: git log master --oneline | wc -l

    - name: test exe
      run: |
        pwd
        ls -al
        ./Localizer
      working-directory: ./blackJack/blackJack/sample

    - name: check xcodeList
      run: ls -n /Applications/ | grep Xcode*
      
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: ./.github/workflows/submitCredential.sh
    - name: fastlane
      run: fastlane tests
      working-directory: ./blackJack
    - name: shell
      run: sh ./UnitTest.sh
      working-directory: ./blackJack
    # - name: test
    #   run: UnitTest.sh
    #   working-directory: ./trcomMobile2
    - name: isXcodebuildExist
      run: xcodebuild -list
      working-directory: ./blackJack