name: Swift

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: #テスト用手動実行イベント

jobs:
  build:
    runs-on: macos-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - name: Cache SwiftPM
      uses: actions/cache@v2
      with: 
        path: |
          ./blackJack/.SPM
        key: ${{ hashFiles('**/Package.resolved') }}
    - name: test exe
      run: |
        pwd
        ls -al
        ./Localizer
      working-directory: ./blackJack/blackJack/sample

    - name: check xcodeList
      run: ls -n /Applications/ | grep Xcode*
      
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: ./.github/workflows/submitCredential.sh
    - name: fastlane
      env:
        PULL_REQUEST_URL: ${{  github.event.pull_request.html_url }}
      run: fastlane tests prUrl:${PULL_REQUEST_URL}
      working-directory: ./blackJack
    - name: UploadFailureReport
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: report.html
        path: ./blackjack/fastlane/test_output/report.html
        retention-days: 7
    # - name: shell
    #   run: sh ./UnitTest.sh
    #   working-directory: ./blackJack
    # - name: test
    #   run: UnitTest.sh
    #   working-directory: ./trcomMobile2
    # - name: isXcodebuildExist
    #   run: xcodebuild -list
    #   working-directory: ./blackJack