name: uploadArtifacts

on:
  workflow_dispatch: #テスト用手動実行イベント
  push:
      branches:
        - master

jobs:
  dump:
    runs-on: macos-latest
    steps:
      - name: dump context
        run: echo '${{ toJSON(github) }}'

  dumpGit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: dump git
        run: |
          git rev-list --count master
          git log --oneline
    
  upload:
    if: github.event_name == 'push'
    name: Add 3 and 7
    runs-on: macos-latest
    environment: test
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  download:
    if: github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    environment: test
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat math-homework.txt`

          echo $value